# Generated by Django 3.1.3 on 2021-02-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='psot',
            new_name='post',
        ),
    ]
